spring:
  flyway:
    user: reciptor
    password: reciptor
    locations: classpath:migrations
    target: 5
  r2dbc:
    url: 'r2dbc:postgresql://localhost/postgres'
    username: reciptor
    password: reciptor
cors:
  allowedOrigins: http://localhost:4200
  allowedMethods: POST, PUT, GET, OPTIONS, DELETE, HEAD

reciptor:
  password:
    encoder:
      secret: ${RECIPTOR_ENCODER_SECRET}
      iteration: ${RECIPTOR_ENCODER_ITERATION}
      keylength: ${RECIPTOR_ENCODER_KEYLENGTH}
  jwt:
    secret: ${RECIPTOR_JWT_SECRET}
    expiration: ${RECIPTOR_JWT_EXPIRATION}


