spring:
  flyway:
    user: reciptor
    password: reciptor
    locations: classpath:migrations
  r2dbc:
    url: 'r2dbc:postgresql://localhost/postgres'
    username: reciptor
    password: reciptor
cors:
  allowedOrigins: http://localhost:4200
  allowedMethods: POST, PUT, GET, OPTIONS, DELETE, HEAD

