language: java
jdk:
  - openjdk11
env: NODE_VERSION="15"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - ./node_modules
before_install:
  - nvm install $NODE_VERSION
  - npm install -g @nrwl/cli

install:
  - npm install

script:
  - nx run-many --target test --all --no-cache
