language: java
jdk:
  - openjdk11
env: NODE_VERSION="15"
git:
  depth: false

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - ./node_modules
before_install:
  - nvm install $NODE_VERSION
  - npm install -g @nrwl/cli

install:
  - npm install
stages:
  - lint
  - test
jobs:
  include:
    - stage: lint
      script: npm run affected:lint -- --plain --base=develop
    - stage: test
      script: npm run affected:test -- --plain --base=develop
